jobs:
  include:
    language:
    python:
    env:
      - TESTS="Docker"
    services:
      - docker
    before_install:
    before_script:
    install:
    script:
      - docker build -f Dockerfile -t openwpm . && docker build -f Dockerfile-dev -t openwpm-dev .
